name: nyxx_extensions
version: 3.2.0
description: Nyxx Extensions Module. Discord library for Dart. Simple, robust framework for creating discord bots for Dart language.
homepage: https://github.com/nyxx-discord/nyxx
repository: https://github.com/nyxx-discord/nyxx
documentation: https://nyxx.l7ssha.xyz
issue_tracker: https://github.com/nyxx-discord/nyxx/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  http: ^0.13.3
  nyxx: ^5.0.0

dev_dependencies:
  coverage: ^1.0.3
  lints: ^2.0.1
  test: ^1.17.0
